### ISSUE TITLE
Doesn't work when audio is playing 

### ISSUE THREAD

**Issue by Venator777** [smasher164/pw-volume#12]
Everything works as expected when no audio is playing. However, if I for example have firefox open with any audio playing, any attempt to run it results in this message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to determine default audio sink', src/main.rs:319:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

In the case of Firefox, stopping the audio does not help, Firefox has to be fully closed before it starts working again. In the case of some other programs, as long as the audio is not playing, I can still change the volume. 

I also noticed that the volume is really loud, a 'normal' volume level would be at around 0.5% but I think this is something with my alsa setup and not related to the issue.

**Comment by smasher164** [comment]
Thanks for reporting this! I’m going to try to reproduce and see if this is alsa-specific.

A couple questions if you don’t mind:
* Does this behavior occur with both the v0.1.0 and v0.2.0 releases? I ask because v0.2.0 tries to mimick pactl and adjust pipewire’s channel volumes instead of volume.
* What command do you typically use to adjust volume on your system?
* What happens if you manually try to read the value of `default.audio.sink` from `pw-dump` when firefox is playing audio? I’m surprised it’s not visible.

**Comment by Venator777** [comment]
- I'm not sure, unfortunately I'm very unfamiliar with rust so not exactly sure how to compile release 0.1, but I'll try to tomorrow.
- At the moment I don't have a go to set up, I've been either using pw-cli directly (adjusting the channels) or amixer. I'm trying to avoid having pulseaudio installed. 
- Interestingly, the output of pw-dump | grep default.audio.sink is always the same, audio playing or not: 
 `{ "subject": 0, "key": "default.audio.sink", "type": "Spa:String:JSON", "value": { "name": "alsa_output.pci-0000_10_00.4.analog-stereo" } },`

**Comment by smasher164** [comment]
* There are binaries for both releases on this repo btw :)

https://github.com/smasher164/pw-volume/releases

* Wait that's perfect then. Since, I'm using pw-cli under the hood, we can probably figure out where the discrepancy is.

* That's definitely weird, since pw-volume literally just calls pw-dump and grabs that field. Maybe there's some false assumption about the output of pw-dump I'm making?

**Comment by Venator777** [comment]
Ok so the issue occurs on both versions. I just double checked and pw-cli does work when volume is playing, if it helps the exact command I use is:
`
pw-cli s 41 Props '{ mute: false, channelVolumes: [ x.xxx, x.xxx ] }'`

**Comment by smasher164** [comment]
Just so you know, I haven't forgotten about this. I just recently joined a new job, and it'll take some time before I can wind down and attend to this. Hope you can understand!

**Comment by smasher164** [comment]
If you're able to run the `main` branch, please let me know if it fixes your issue.

Thanks!

**Comment by Venator777** [comment]
Just built, yes this fixed the issue, thanks a lot!
